# POST http://localhost:5000/confirm_order
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTEyYTFlMTBhYjljYTJhZjBhM2M4MmMiLCJ1c2VybmFtZSI6ImFrc2hheW1lbWFpbCIsImVtYWlsIjoiYWtzaGF5bWVtYWlsQGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiQUtTQUhZIEtVTUFSIFNJTkdIIiwiaWF0IjoxNjI4NjExMzc2LCJleHAiOjE2MjkyMTYxNzZ9.G9-qF3a9e1phCl8D8cmDgo4S1HYq3u_UR2mfGRfgHE0

GET http://localhost:5000/order_history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTEyYjljYmY1MDdjOTI4YmM1ZTBhYjYiLCJ1c2VybmFtZSI6InNpZGRoYXJ0aCIsImVtYWlsIjoianNpZGQwNkBnbWFpbC5jb20iLCJmdWxsbmFtZSI6IlNpZGRoYXJ0aCBqYWluIiwiaWF0IjoxNjI4NjUwOTIwLCJleHAiOjE2MjkyNTU3MjB9.WEUHMMdhDj-4ZeJMq4NhZHi8Wtq3dYYE-_nm4GyD_ME